Update to use FML without event transformers for now (broken)
Pointing to commit:

deathcap/FML@a02af748686647ef8e4c4f91bd14212739895e0d Disable ASM event transformers for now

Disabled since these cause ClassCircularityErrors for some reason:

21:26:57] [main/ERROR] [LaunchWrapper]: A critical problem occurred registering the ASM transformer class $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
java.lang.ClassNotFoundException: $wrapper.net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_72]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_72]
	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88) [glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:118) [glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_72]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_72]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_72]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_72]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at net.glowstone.GlowServer.main(GlowServer.java:105) [glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer@e0e37b3 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:234) ~[glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	... 13 more
Caused by: java.lang.ClassCircularityError: net/minecraftforge/fml/common/eventhandler/Event
	at net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer.buildEvents(EventSubscriptionTransformer.java:85) ~[glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer.transform(EventSubscriptionTransformer.java:62) ~[glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:230) ~[glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	... 13 more
[21:26:57] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.RuntimeException: java.lang.ClassNotFoundException: net.minecraftforge.fml.common.asm.FMLSanityChecker
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:155) ~[glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_72]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_72]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_72]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_72]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at net.glowstone.GlowServer.main(GlowServer.java:105) [glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.common.asm.FMLSanityChecker
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_72]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_72]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_72]
	at java.lang.Class.forName(Class.java:274) ~[?:1.7.0_72]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:143) ~[glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	... 9 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.BlamingTransformer@357c4ab7 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:234) ~[glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_72]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_72]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_72]
	at java.lang.Class.forName(Class.java:274) ~[?:1.7.0_72]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:143) ~[glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	... 9 more
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/JavaVersion
	at net.minecraftforge.fml.common.asm.transformers.BlamingTransformer$VersionVisitor.visit(BlamingTransformer.java:60) ~[glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:622) ~[glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:506) ~[glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at net.minecraftforge.fml.common.asm.transformers.BlamingTransformer.transform(BlamingTransformer.java:39) ~[glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:230) ~[glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_72]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_72]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_72]
	at java.lang.Class.forName(Class.java:274) ~[?:1.7.0_72]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:143) ~[glowstone-0.0.1-SNAPSHOT.jar:git-Glowstone-1.8-225-g2125021]
	... 9 more
21:26:57 [INFO] This server is running Glowstone version git-Glowstone-1.8-225-g2125021 (Implementing API version 1.8-R1-SNAPSHOT)
21:26:58 [INFO] Recipes: 295 shaped, 63 shapeless, 24 furnace, 15 fuels.